# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cabdb72bdc2b79fdc182e3419f6146f89490992171b7dd228a95d4dd23eec08d30dbf79aa19f9751e5fca9995e92a5f58557734f00c11074ae28a30147bcbf1

test:
  secret_key_base: 2409667b0fea1b8785edffda1271e87de0703a625027eebfa5ea5cb7aa7832fb70ebc2bd9fe3eff245a05adc937467c64bb3f16481cace2a1de9024da2e17ad4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
